name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  ip-get-super-super:
    runs-on: ubuntu-latest
    steps:
      #checkout必須
      - uses: actions/checkout@v3
      #node.jsをセットアップする
      - uses: actions/setup-node@v3
      - run : npm install marked@4.0
      - run : npm install commander@9.0
      - run : node builder-takuya/takuya.mjs --gfm src/first.md
      #- run: ls /home/runner/work/actions-test/actions-test/
      #- run: python3 test/unko.py