name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  ip-get-super-super:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: python3 test/unko.py
