name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
steps:
  - uses: actions/checkout@v3
jobs:
  ip-get-super-super:
    runs-on: ubuntu-latest
    steps:
      - run: ls /home/runner/work/actions-test/